### ISSUE TITLE
No module named bootstrap3shop 

### ISSUE THREAD

**Issue by smilemakc** [dyve/django-bootstrap3#288]
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/balashov/.pyenv/versions/childhoodEnv/lib/python3.4/site-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "/Users/balashov/.pyenv/versions/childhoodEnv/lib/python3.4/site-packages/django/core/management/__init__.py", line 324, in execute
    django.setup()
  File "/Users/balashov/.pyenv/versions/childhoodEnv/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/balashov/.pyenv/versions/childhoodEnv/lib/python3.4/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/Users/balashov/.pyenv/versions/childhoodEnv/lib/python3.4/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/Users/balashov/.pyenv/versions/3.4.2/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2224, in _find_and_load_unlocked
ImportError: No module named 'bootstrap3shop'

**Comment by adriaant** [comment]
You should check your settings. 'bootstrap3' is de right app notation, so looks like a typo in your own settings file.

**Comment by smilemakc** [comment]
INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bootstrap3'
    'childhood',
)

**Comment by dyve** [comment]
You need a comma after 'bootstrap3'

**Comment by smilemakc** [comment]
only sh....
of course. very stupid typo. thank you!
