### ISSUE TITLE
Issues calling bootstrap3

### ISSUE THREAD

**Issue by Jzarecta** [dyve/django-bootstrap3#320]
I want to know how can I get bootstrap3 in my templates, I added on INSTALLED_APPS and template/product_form.htm and added the example {% load bootstrap3 %} but returned the following error:
I am using python 2.7.9 and django 1.9:
```
$ python manage.py runserver 0.0.0.0:8181
Unhandled exception in thread started by <function wrapper at 0x7f17d442fed8>
Traceback (most recent call last):
  File "/home/dsiav/crud/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/dsiav/crud/local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/home/dsiav/crud/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/home/dsiav/crud/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/dsiav/crud/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/dsiav/crud/local/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/dsiav/crud/local/lib/python2.7/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named boostrap3
```

**Comment by adriaant** [comment]
It says "boostrap3", not "bootstrap3"
